### ISSUE TITLE
Add contributor to repo

### ISSUE THREAD

**Issue by droumis** [ProjectPythia/landsat-ml-cookbook#15]
Hi @r-ford, apologies if this is not the right way to do it. How should I request a colleague be given push permissions to this repository? Her handle is @sandhujasmine

Would you prefer such requests go through the Pangeo Discourse in the future?

Thank you!

**Comment by r-ford** [comment]
Hi @droumis, I just changed your role on this repo to Admin, so I think that gives permission to add people. Let me know if you can't.

I'm not sure if we decided how cookbook roles/permissions should work yet, but I'll talk to the rest of the Pythia team about it.

**Comment by droumis** [comment]
thank you!

**Comment by r-ford** [comment]
Hey @droumis, in case you're wondering why I sent you another invitation to the organization, we decided that cookbook authors should be full members of the organization (if you want!) instead of the "outside collaborator" role. This is just to simplify organization permissions.
